### ISSUE TITLE
Access not possible

### ISSUE THREAD

**Issue by Mands59** [LINCnil/pia-back#66] opened 2019-04-22 21:54 UTC
When i rails serve in production, i can't access the url, but the serve is rails and it's say that i can access it in the url

**Comment by Mands59** [comment] 2019-04-22 22:06
In development there is no prob, just in production … *

**Comment by brunto** [comment] 2019-04-23 08:28
Hi, We need more information to help you.
Could you provide some screenshot or any commands you used?

**Comment by Mands59** [comment] 2019-04-23 09:18
When i run `bin/rails s -e production -b XX.XX.XX.XX -p XXXX` i can't access the url, but when i run just `bin/rails s -b XX.XX.XX.XX -p XXXX` i can access, but it's not in production, it's in development method…

**Comment by Mands59** [comment] 2019-04-23 09:20
![image](https://user-images.githubusercontent.com/49683019/56569687-c467c180-65b9-11e9-8cbb-ff9168c6c691.png)

**Comment by brunto** [comment] 2019-04-23 09:33
In production mode what's happen on your browser? Do you have some logs messages?

**Comment by Mands59** [comment] 2019-04-23 09:36
I never had logs message

**Comment by Mands59** [comment] 2019-04-23 09:39
in dev mode i have : 
![dev](https://user-images.githubusercontent.com/49683019/56571061-743e2e80-65bc-11e9-8696-a98d486ca152.PNG)


and in prod mode :
![prod](https://user-images.githubusercontent.com/49683019/56571082-7f915a00-65bc-11e9-9f3a-3b1c128450af.PNG)

**Comment by brunto** [comment] 2019-04-23 09:50
Could you try with `RAILS_ENV=production bin/rails s -b XX.XX.XX.XX -p XXXX` ?

**Comment by Mands59** [comment] 2019-04-23 09:53
with `RAILS_ENV=production bin/rails s -b XX.XX.XX.XX -p XXXX` i have this : 
![prod 2](https://user-images.githubusercontent.com/49683019/56572003-6be6f300-65be-11e9-96ae-a32aeeeb4bd4.PNG)

**Comment by brunto** [comment] 2019-04-23 10:18
Really, I don't understand what's happen! I haven't any solutions!
BTW you can use pia-back in dev mode until someone have an idea.

**Comment by sposs** [comment] 2019-04-24 14:51
The issue is that the default route '/' must be defined explicitly for production. In dev/test, this is the public/index.html. BTW, in the doc, it is explicitly said not to keep that file, and make it a real view. https://stackoverflow.com/a/6257744/7716313

**Comment by sposs** [comment] 2019-04-24 15:00
I'm not a ruby expert at all, but I found a 'fix'.
To be more explicit, I added this in the routes.rb:
```ruby
root :controller => 'static', :action => 'index'
```
I also added app/controllers/static_controller.rb with content
```ruby
class StaticController < ActionController::API
   def index
      render "/public/index.html"
   end
end
```
Even if it does not render anything really, it's enough to return status code 200, and the client is happy.

**Comment by brunto** [comment] 2019-06-03 08:50
Thx for your help, this is fixed in the next release.

**Closed** 2019-10-08 12:57 UTC
