### ISSUE TITLE
Different version information displayed on top of the page compared to the release

### ISSUE THREAD

**Issue by smilnovi** [LINCnil/pia-back#51] opened 2019-02-18 14:25 UTC
Hi,

We have noticed that for the 2.0.0 release the site displays version 1.6.0 on the left top of the page. Could you please let me know if this is expected?

**Comment by brunto** [comment] 2019-02-20 08:55
Hi,
I can't reproduce this! If you have the number version 1.6 on your software it means that this is the version 1.6.

**Comment by smilnovi** [comment] 2019-02-20 09:06
Hi Brunto,

We have pulled the source code from git as is described in the manual and as I have mentioned, we can see the version 1.6.0. Should we perhaps had to take the "release" archive? How can we in the source code confirm we have 2.0.0 release and not 1.6.0?

**Comment by brunto** [comment] 2019-02-20 09:27
I confirm that the current package.json show the number 1.6.4 https://github.com/LINCnil/pia/blob/master/package.json#L3 I will change this.
You can also set your version number https://github.com/LINCnil/pia#build-for-production
But I confirm you that if you are on the master branch you are on the version 2 of the application.

**Comment by smilnovi** [comment] 2019-02-20 09:31
Hi Brunto,

Thank you very much for the confirmation and fix. Should you close this one or should I do so?

**Comment by brunto** [comment] 2019-02-20 09:33
You're welcome. I close this issue. Thanks for your help.

**Closed by brunto** 2019-02-20 09:33 UTC
